{
 "title": "CloudFront Summary",
 "tags": [
  "siem",
  "converted-from-opensearch-dashboards"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "CloudFront - AWS Account(Bar)",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "cloud.account.id",
       "id": "2",
       "settings": {
        "min_doc_count": "1",
        "missing": "",
        "order": "desc",
        "orderBy": "_count",
        "size": "10"
       },
       "type": "terms"
      },
      {
       "field": "cloud.account.id",
       "id": "3",
       "settings": {
        "min_doc_count": "1",
        "missing": "",
        "order": "desc",
        "orderBy": "_count",
        "size": "10"
       },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "CloudFront - Edge Location(Bar)",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "x_edge_location",
       "id": "3",
       "settings": {
        "min_doc_count": "1",
        "missing": "",
        "order": "desc",
        "orderBy": "_count",
        "size": "10"
       },
       "type": "terms"
      },
      {
       "field": "x_edge_location",
       "id": "2",
       "settings": {
        "min_doc_count": "1",
        "missing": "",
        "order": "desc",
        "orderBy": "_count",
        "size": "10"
       },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "CloudFront - Distribution Domain Name",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "distribution_id",
       "id": "3",
       "settings": {
        "min_doc_count": "1",
        "missing": "",
        "order": "desc",
        "orderBy": "_count",
        "size": "100"
       },
       "type": "terms"
      },
      {
       "field": "url.domain",
       "id": "5",
       "settings": {
        "min_doc_count": "1",
        "missing": "",
        "order": "desc",
        "orderBy": "_count",
        "size": "10"
       },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "CloudFront - Status Code Trend",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "http.response.status_code",
       "id": "3",
       "settings": {
        "min_doc_count": "1",
        "missing": "",
        "order": "desc",
        "orderBy": "_count",
        "size": "10"
       },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "CloudFront - Request Size",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "http.request.bytes", "id": "1", "meta": { "customLabel": "Request Size(GiB)" }, "type": "sum" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "CloudFront - Status Code (Pie)",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 16 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "http.response.status_code",
       "id": "2",
       "settings": {
        "min_doc_count": "1",
        "missing": "",
        "order": "desc",
        "orderBy": "_count",
        "size": "5"
       },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "CloudFront - Result Type(Pie)",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 16 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "x_edge_result_type",
       "id": "2",
       "settings": {
        "min_doc_count": "1",
        "missing": "",
        "order": "desc",
        "orderBy": "_count",
        "size": "10"
       },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "CloudFront - Response Size",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "http.response.bytes", "id": "1", "meta": { "customLabel": "Response Size(GiB)" }, "type": "sum" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "CloudFront - Response Time (seconds)",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "x_edge_result_type",
       "id": "2",
       "settings": {
        "min_doc_count": "1",
        "missing": "",
        "order": "desc",
        "orderBy": "_count",
        "size": "10"
       },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "time_taken", "id": "1", "meta": { "customLabel": "Response Time" }, "type": "percentiles" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "CloudFront - URL Scheme(Pie)",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 36 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "url.scheme",
       "id": "2",
       "settings": {
        "min_doc_count": "1",
        "missing": "",
        "order": "desc",
        "orderBy": "_count",
        "size": "10"
       },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "CloudFront - SSL Protocol(Pie)",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 36 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "ssl_protocol",
       "id": "2",
       "settings": {
        "min_doc_count": "1",
        "missing": "",
        "order": "desc",
        "orderBy": "_count",
        "size": "10"
       },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "CloudFront - SSL Cipher",
   "type": "table",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 36 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "ssl_cipher",
       "id": "2",
       "settings": {
        "min_doc_count": "1",
        "missing": "",
        "order": "desc",
        "orderBy": "_count",
        "size": "30"
       },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "CloudFront - Source IP(Pie)",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 6, "x": 18, "y": 36 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "source.ip",
       "id": "2",
       "settings": {
        "min_doc_count": "1",
        "missing": "",
        "order": "desc",
        "orderBy": "_count",
        "size": "10"
       },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "CloudFront - Top 10 Access",
   "type": "table",
   "gridPos": { "h": 14, "w": 18, "x": 0, "y": 46 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "http.request.method",
       "id": "4",
       "settings": {
        "min_doc_count": "1",
        "missing": "",
        "order": "desc",
        "orderBy": "_count",
        "size": "10"
       },
       "type": "terms"
      },
      {
       "field": "url.domain",
       "id": "2",
       "settings": {
        "min_doc_count": "1",
        "missing": "",
        "order": "desc",
        "orderBy": "_count",
        "size": "10"
       },
       "type": "terms"
      },
      {
       "field": "url.path",
       "id": "3",
       "settings": {
        "min_doc_count": "1",
        "missing": "",
        "order": "desc",
        "orderBy": "_count",
        "size": "10"
       },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "CloudFront - Source Country(Pie)",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 6, "x": 18, "y": 48 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "source.geo.country_iso_code",
       "id": "2",
       "settings": {
        "min_doc_count": "1",
        "missing": "",
        "order": "desc",
        "orderBy": "_count",
        "size": "10"
       },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "CloudFront - Top 10 Referer",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 60 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "http.request.referrer",
       "id": "2",
       "settings": {
        "min_doc_count": "1",
        "missing": "",
        "order": "desc",
        "orderBy": "_count",
        "size": "10"
       },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "CloudFront - Top 10 UserAgent",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 60 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "user_agent.original",
       "id": "2",
       "settings": {
        "min_doc_count": "1",
        "missing": "",
        "order": "desc",
        "orderBy": "_count",
        "size": "10"
       },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "CloudFront - UserAgent (PIE)",
   "type": "piechart",
   "gridPos": { "h": 14, "w": 8, "x": 0, "y": 72 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "user_agent.name",
       "id": "2",
       "settings": {
        "min_doc_count": "1",
        "missing": "",
        "order": "desc",
        "orderBy": "_count",
        "size": "10"
       },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "CloudFront - UserAgent OS",
   "type": "piechart",
   "gridPos": { "h": 14, "w": 8, "x": 8, "y": 72 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "user_agent.os.name",
       "id": "2",
       "settings": {
        "min_doc_count": "1",
        "missing": "",
        "order": "desc",
        "orderBy": "_count",
        "size": "10"
       },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "CloudFront - UserAgent Device",
   "type": "piechart",
   "gridPos": { "h": 14, "w": 8, "x": 16, "y": 72 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "user_agent.device.name",
       "id": "2",
       "settings": {
        "min_doc_count": "1",
        "missing": "",
        "order": "desc",
        "orderBy": "_count",
        "size": "10"
       },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "CloudFront - Source Country",
   "type": "geomap",
   "gridPos": { "h": 16, "w": 16, "x": 0, "y": 86 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "source.geo.country_iso_code",
       "id": "2",
       "settings": {
        "min_doc_count": "1",
        "missing": "",
        "order": "desc",
        "orderBy": "_count",
        "size": "100"
       },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "CloudFront - Source Country (Table)",
   "type": "table",
   "gridPos": { "h": 16, "w": 8, "x": 16, "y": 86 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "source.geo.country_name",
       "id": "2",
       "settings": {
        "min_doc_count": "1",
        "missing": "",
        "order": "desc",
        "orderBy": "_count",
        "size": "100"
       },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "CloudFront - Maximum Latency per Country",
   "type": "geomap",
   "gridPos": { "h": 16, "w": 16, "x": 0, "y": 102 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "source.geo.country_iso_code",
       "id": "2",
       "settings": {
        "min_doc_count": "1",
        "missing": "",
        "order": "desc",
        "orderBy": "_count",
        "size": "10"
       },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "time_taken", "id": "1", "meta": { "customLabel": "Maximum Latency (seconds)" }, "type": "max" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "CloudFront - Maximum Latency per Country (Table)",
   "type": "table",
   "gridPos": { "h": 16, "w": 8, "x": 16, "y": 102 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "source.geo.country_name",
       "id": "2",
       "settings": {
        "min_doc_count": "1",
        "missing": "",
        "order": "desc",
        "orderBy": "_count",
        "size": "100"
       },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "time_taken", "id": "1", "meta": { "customLabel": "Maximum Latency (seconds)" }, "type": "max" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "search - CloudFront (distribution_id, url.domain, cs_method, url.path, sc_status, x_edge_result_type, source.ip, source.geo.country_name)",
   "type": "logs",
   "gridPos": { "h": 23, "w": 24, "x": 0, "y": 118 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "type": "logs" }
     ],
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}