{
 "title": "GuardDuty Summary",
 "tags": [
  "siem",
  "converted-from-opensearch-dashboards"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "GuardDuty - AWS Account(Bar)",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "cloud.account.id",
       "id": "2",
       "settings": {
        "min_doc_count": "1",
        "missing": "",
        "order": "desc",
        "orderBy": "_count",
        "size": "5"
       },
       "type": "terms"
      },
      {
       "field": "cloud.account.id",
       "id": "3",
       "settings": {
        "min_doc_count": "1",
        "missing": "",
        "order": "desc",
        "orderBy": "_count",
        "size": "5"
       },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "@id", "id": "1", "meta": { "customLabel": "Count" }, "type": "cardinality" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "GuardDuty - Region(Bar)",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "cloud.region",
       "id": "2",
       "settings": {
        "min_doc_count": "1",
        "missing": "",
        "order": "desc",
        "orderBy": "_count",
        "size": "5"
       },
       "type": "terms"
      },
      {
       "field": "cloud.region",
       "id": "3",
       "settings": {
        "min_doc_count": "1",
        "missing": "",
        "order": "desc",
        "orderBy": "_count",
        "size": "5"
       },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "@id", "id": "1", "meta": { "customLabel": "Count" }, "type": "cardinality" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "GuardDuty - Findings",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "metrics": [
      { "field": "@id", "id": "1", "meta": { "customLabel": " " }, "type": "cardinality" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "GuardDuty - Severity Count by Findings",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "metrics": [
      { "field": "@id", "id": "1", "meta": { "customLabel": " " }, "type": "cardinality" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "GuardDuty - Severity Count by Logs",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "meta": { "customLabel": " " }, "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "GuardDuty - Severity Count by Logs (Bar)",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "GuardDuty - Network Direction",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 29 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "network.direction",
       "id": "2",
       "settings": {
        "min_doc_count": "1",
        "missing": "",
        "order": "desc",
        "orderBy": "_count",
        "size": "5"
       },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "@id", "id": "1", "meta": { "customLabel": "Count" }, "type": "cardinality" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "GuardDuty - Affected Instance",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 29 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "resource.instanceDetails.instanceId",
       "id": "2",
       "settings": {
        "min_doc_count": "1",
        "missing": "",
        "order": "desc",
        "orderBy": "_count",
        "size": "10"
       },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "GuardDuty - ThreatPurpose",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 29 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "ThreatPurpose",
       "id": "2",
       "settings": {
        "min_doc_count": "1",
        "missing": "",
        "order": "desc",
        "orderBy": "_count",
        "size": "30"
       },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "GuardDuty - ThreatFamilyName",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 29 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "ThreatFamilyName",
       "id": "2",
       "settings": {
        "min_doc_count": "1",
        "missing": "",
        "order": "desc",
        "orderBy": "_count",
        "size": "30"
       },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "@id", "id": "1", "meta": { "customLabel": "Count" }, "type": "cardinality" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "GuardDuty - Resource Type Affected",
   "type": "table",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 35 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "ResourceTypeAffected",
       "id": "2",
       "settings": {
        "min_doc_count": "1",
        "missing": "",
        "order": "desc",
        "orderBy": "_count",
        "size": "10"
       },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "@id", "id": "1", "meta": { "customLabel": "Count" }, "type": "cardinality" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "GuardDuty - Source Countries Geo Map",
   "type": "geomap",
   "gridPos": { "h": 19, "w": 18, "x": 6, "y": 38 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "source.geo.country_iso_code",
       "id": "2",
       "settings": {
        "min_doc_count": "1",
        "missing": "",
        "order": "desc",
        "orderBy": "_count",
        "size": "100"
       },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "@id", "id": "1", "meta": { "customLabel": "Count" }, "type": "cardinality" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "GuardDuty - Type Table",
   "type": "table",
   "gridPos": { "h": 13, "w": 6, "x": 0, "y": 44 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "type",
       "id": "2",
       "settings": {
        "min_doc_count": "1",
        "missing": "",
        "order": "desc",
        "orderBy": "_count",
        "size": "120"
       },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "GuardDuty - user.name",
   "type": "table",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 57 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "user.name",
       "id": "2",
       "settings": {
        "min_doc_count": "1",
        "missing": "",
        "order": "desc",
        "orderBy": "_count",
        "size": "5"
       },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "GuardDuty - user.id",
   "type": "table",
   "gridPos": { "h": 11, "w": 5, "x": 6, "y": 57 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "user.id",
       "id": "2",
       "settings": {
        "min_doc_count": "1",
        "missing": "",
        "order": "desc",
        "orderBy": "_count",
        "size": "5"
       },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "GuardDuty - source",
   "type": "table",
   "gridPos": { "h": 11, "w": 6, "x": 11, "y": 57 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "source.ip",
       "id": "2",
       "settings": {
        "min_doc_count": "1",
        "missing": "",
        "order": "desc",
        "orderBy": "_count",
        "size": "100"
       },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "source.geo.country_name", "id": "4", "meta": { "customLabel": "Country" }, "type": "top_hits" },
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "GuardDuty - destination",
   "type": "table",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 57 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "destination.ip",
       "id": "2",
       "settings": {
        "min_doc_count": "1",
        "missing": "",
        "order": "desc",
        "orderBy": "_count",
        "size": "100"
       },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "destination.geo.country_name", "id": "4", "meta": { "customLabel": "Country" }, "type": "top_hits" },
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "GuardDuty - EKS Cluster Name",
   "type": "table",
   "gridPos": { "h": 13, "w": 8, "x": 0, "y": 68 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "resource.eksClusterDetails.name",
       "id": "2",
       "settings": {
        "min_doc_count": "1",
        "missing": "",
        "order": "desc",
        "orderBy": "_count",
        "size": "100"
       },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "GuardDuty - Malware name",
   "type": "table",
   "gridPos": { "h": 13, "w": 8, "x": 8, "y": 68 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "service.ebsVolumeScanDetails.scanDetections.threatDetectedByName.threatNames.name",
       "id": "2",
       "settings": {
        "min_doc_count": "1",
        "missing": "",
        "order": "desc",
        "orderBy": "_count",
        "size": "100"
       },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "GuardDuty - S3 Bucket Name",
   "type": "table",
   "gridPos": { "h": 13, "w": 8, "x": 16, "y": 68 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "resource.s3BucketDetails.name",
       "id": "2",
       "settings": {
        "min_doc_count": "1",
        "missing": "",
        "order": "desc",
        "orderBy": "_count",
        "size": "100"
       },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "search - GuardDuty (cloud.account.id, severitylabel, type, cloud.instance.id, service.count, source.ip, source.geo.country_name)",
   "type": "logs",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 81 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "type": "logs" }
     ],
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}