{
 "title": "VPCFlowLogs Summary",
 "tags": [
  "siem",
  "converted-from-opensearch-dashboards"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "VPCFlowLogs - AWS Account(Bar)",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "cloud.account.id",
       "id": "2",
       "settings": {
        "min_doc_count": "1",
        "missing": "",
        "order": "desc",
        "orderBy": "_count",
        "size": "5"
       },
       "type": "terms"
      },
      {
       "field": "cloud.account.id",
       "id": "3",
       "settings": {
        "min_doc_count": "1",
        "missing": "",
        "order": "desc",
        "orderBy": "_count",
        "size": "10"
       },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "VPCFlowLogs - Region(Bar)",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "cloud.region",
       "id": "2",
       "settings": {
        "min_doc_count": "1",
        "missing": "",
        "order": "desc",
        "orderBy": "_count",
        "size": "5"
       },
       "type": "terms"
      },
      {
       "field": "cloud.region",
       "id": "3",
       "settings": {
        "min_doc_count": "1",
        "missing": "",
        "order": "desc",
        "orderBy": "_count",
        "size": "5"
       },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "VPCFlowLogs - Accept Packets(Line Chart)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "sum_bucket" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "VPCFlowLogs - Reject Packets(Line Chart)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "sum_bucket" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "VPCFlowLogs - Accept Src Packets(Pie)",
   "type": "piechart",
   "gridPos": { "h": 13, "w": 6, "x": 0, "y": 15 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "source.ip",
       "id": "2",
       "settings": {
        "min_doc_count": "1",
        "missing": "",
        "order": "desc",
        "orderBy": "_count",
        "size": "10"
       },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "source.packets", "id": "1", "type": "sum" }
     ],
     "query": "action:ACCEPT",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "VPCFlowLogs - Accept Src Packets(Table)",
   "type": "table",
   "gridPos": { "h": 13, "w": 6, "x": 6, "y": 15 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "source.ip",
       "id": "2",
       "settings": {
        "min_doc_count": "1",
        "missing": "",
        "order": "desc",
        "orderBy": "_count",
        "size": "10"
       },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "source.packets", "id": "1", "meta": { "customLabel": "Packets" }, "type": "sum" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "VPCFlowLogs - Reject Src Packets(Pie)",
   "type": "piechart",
   "gridPos": { "h": 13, "w": 6, "x": 12, "y": 15 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "source.ip",
       "id": "2",
       "settings": {
        "min_doc_count": "1",
        "missing": "",
        "order": "desc",
        "orderBy": "_count",
        "size": "10"
       },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "source.packets", "id": "1", "type": "sum" }
     ],
     "query": "action:REJECT",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "VPCFlowLogs - Reject Src Packets(Table)",
   "type": "table",
   "gridPos": { "h": 13, "w": 6, "x": 18, "y": 15 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "source.ip",
       "id": "2",
       "settings": {
        "min_doc_count": "1",
        "missing": "",
        "order": "desc",
        "orderBy": "_count",
        "size": "10"
       },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "source.packets", "id": "1", "meta": { "customLabel": "Packets" }, "type": "sum" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "VPCFlowLogs - Accept Src Packets(Geo)",
   "type": "geomap",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 28 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "source.geo.country_iso_code",
       "id": "2",
       "settings": {
        "min_doc_count": "1",
        "missing": "",
        "order": "desc",
        "orderBy": "_count",
        "size": "100"
       },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "source.packets", "id": "1", "type": "sum" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "VPCFlowLogs - Reject Src Packets(Geo)",
   "type": "geomap",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 28 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "source.geo.country_iso_code",
       "id": "2",
       "settings": {
        "min_doc_count": "1",
        "missing": "",
        "order": "desc",
        "orderBy": "_count",
        "size": "100"
       },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "source.packets", "id": "1", "type": "sum" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "VPCFlowLogs - Top 10 Chart Source IP",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 43 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" },
      {
       "field": "source.ip",
       "id": "3",
       "settings": {
        "min_doc_count": "1",
        "missing": "",
        "order": "desc",
        "orderBy": "_count",
        "size": "5"
       },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}