{
 "title": "All - Threat Hunting",
 "tags": [
  "siem",
  "converted-from-opensearch-dashboards"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "All - AWS Account",
   "type": "table",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "cloud.account.id",
       "id": "2",
       "settings": {
        "min_doc_count": "1",
        "missing": "",
        "order": "desc",
        "orderBy": "_count",
        "size": "5"
       },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "All - AWS Region",
   "type": "table",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "cloud.region",
       "id": "2",
       "settings": {
        "min_doc_count": "1",
        "missing": "",
        "order": "desc",
        "orderBy": "_count",
        "size": "5"
       },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "All - LogType",
   "type": "table",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "@log_type",
       "id": "2",
       "settings": {
        "min_doc_count": "1",
        "missing": "",
        "order": "desc",
        "orderBy": "_count",
        "size": "5"
       },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "GuardDuty - Type Table",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "type",
       "id": "2",
       "settings": {
        "min_doc_count": "1",
        "missing": "",
        "order": "desc",
        "orderBy": "_count",
        "size": "120"
       },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "All - Source IP",
   "type": "table",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 8 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "source.ip",
       "id": "2",
       "settings": {
        "min_doc_count": "1",
        "missing": "",
        "order": "desc",
        "orderBy": "_count",
        "size": "15"
       },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "All - Source Countries",
   "type": "table",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 8 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "source.geo.country_name",
       "id": "2",
       "settings": {
        "min_doc_count": "1",
        "missing": "",
        "order": "desc",
        "orderBy": "_count",
        "size": "20"
       },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "All - Source AS Organization",
   "type": "table",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 8 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "source.as.organization.name",
       "id": "2",
       "settings": {
        "min_doc_count": "1",
        "missing": "",
        "order": "desc",
        "orderBy": "_count",
        "size": "10"
       },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "All - Destination IP table",
   "type": "table",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 8 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "destination.ip",
       "id": "2",
       "settings": {
        "min_doc_count": "1",
        "missing": "",
        "order": "desc",
        "orderBy": "_count",
        "size": "10"
       },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "All - Destination Countries",
   "type": "table",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 8 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "destination.geo.country_name",
       "id": "2",
       "settings": {
        "min_doc_count": "1",
        "missing": "",
        "order": "desc",
        "orderBy": "_count",
        "size": "10"
       },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "All - Destination AS Organization",
   "type": "table",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 8 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "destination.as.organization.name",
       "id": "2",
       "settings": {
        "min_doc_count": "1",
        "missing": "",
        "order": "desc",
        "orderBy": "_count",
        "size": "10"
       },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "VPCFlowLogs - Action Table",
   "type": "table",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 16 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "action",
       "id": "2",
       "settings": {
        "min_doc_count": "1",
        "missing": "",
        "order": "desc",
        "orderBy": "_count",
        "size": "5"
       },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "VPCFlowLogs - Sent Size via VPC",
   "type": "table",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 16 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "source.ip",
       "id": "2",
       "settings": {
        "min_doc_count": "1",
        "missing": "",
        "order": "desc",
        "orderBy": "_count",
        "size": "10"
       },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "source.bytes", "id": "1", "meta": { "customLabel": "Bytes" }, "type": "sum" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "VPCFlowLogs - Recieved Size via VPC",
   "type": "table",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 16 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "destination.ip",
       "id": "2",
       "settings": {
        "min_doc_count": "1",
        "missing": "",
        "order": "desc",
        "orderBy": "_count",
        "size": "10"
       },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "network.bytes", "id": "1", "meta": { "customLabel": "Bytes" }, "type": "sum" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "S3Trail - Bucket Access Count",
   "type": "table",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 16 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "requestParameters.bucketName",
       "id": "2",
       "settings": {
        "min_doc_count": "1",
        "missing": "",
        "order": "desc",
        "orderBy": "_count",
        "size": "10"
       },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "S3Trail - Upload",
   "type": "table",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 16 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "source.ip",
       "id": "2",
       "settings": {
        "min_doc_count": "1",
        "missing": "",
        "order": "desc",
        "orderBy": "_count",
        "size": "10"
       },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "additionalEventData.bytesTransferredIn",
       "id": "1",
       "meta": { "customLabel": "Upload" },
       "type": "sum"
      }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "S3Trail - Download",
   "type": "table",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 16 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "source.ip",
       "id": "2",
       "settings": {
        "min_doc_count": "1",
        "missing": "",
        "order": "desc",
        "orderBy": "_count",
        "size": "10"
       },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "additionalEventData.bytesTransferredOut",
       "id": "1",
       "meta": { "customLabel": "Download" },
       "type": "sum"
      }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "search - _ECS Fields (cloud.account.id, @log_type, event.module, rule.name, source.ip, source.geo.country_name, cloud.instance.id, user.id, user.name)",
   "type": "logs",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "type": "logs" }
     ],
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}