{
 "title": "Web Summary",
 "tags": [
  "siem",
  "converted-from-opensearch-dashboards"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Web - AWS Account(Bar)",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "cloud.account.id",
       "id": "2",
       "settings": {
        "min_doc_count": "1",
        "missing": "",
        "order": "desc",
        "orderBy": "_count",
        "size": "10"
       },
       "type": "terms"
      },
      {
       "field": "cloud.account.id",
       "id": "3",
       "settings": {
        "min_doc_count": "1",
        "missing": "",
        "order": "desc",
        "orderBy": "_count",
        "size": "10"
       },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Web - Region(Bar)",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "cloud.region",
       "id": "2",
       "settings": {
        "min_doc_count": "1",
        "missing": "",
        "order": "desc",
        "orderBy": "_count",
        "size": "10"
       },
       "type": "terms"
      },
      {
       "field": "cloud.region",
       "id": "3",
       "settings": {
        "min_doc_count": "1",
        "missing": "",
        "order": "desc",
        "orderBy": "_count",
        "size": "10"
       },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Web - Control Panel",
   "type": "text",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 7 },
   "options": {
    "content": "### Web - Control Panel\n\nOpenSearch Dashboards visualization type `input_control_vis` has no automatic Grafana mapping."
   }
  },
  {
   "title": "Web - Access Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 13 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "meta": { "customLabel": "Access Count" }, "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Web - Scheme ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 10, "x": 8, "y": 13 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "url.scheme",
       "id": "2",
       "settings": {
        "min_doc_count": "1",
        "missing": "",
        "order": "desc",
        "orderBy": "_count",
        "size": "2"
       },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Web - Error Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 13 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "meta": { "customLabel": "Error Count" }, "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Web - Response Status Code",
   "type": "piechart",
   "gridPos": { "h": 14, "w": 10, "x": 0, "y": 17 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "http.response.status_code",
       "id": "2",
       "settings": {
        "min_doc_count": "1",
        "missing": "",
        "order": "desc",
        "orderBy": "_count",
        "size": "20"
       },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Web - Request Method(Pie)",
   "type": "piechart",
   "gridPos": { "h": 14, "w": 10, "x": 10, "y": 17 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "http.request.method",
       "id": "2",
       "settings": {
        "min_doc_count": "1",
        "missing": "",
        "order": "desc",
        "orderBy": "_count",
        "size": "20"
       },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Web - Log Level",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 17 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "log.level",
       "id": "2",
       "settings": {
        "min_doc_count": "1",
        "missing": "",
        "order": "desc",
        "orderBy": "_count",
        "size": "10"
       },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Web - Apache Error Module",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 24 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "apache.error.module",
       "id": "2",
       "settings": {
        "min_doc_count": "1",
        "missing": "",
        "order": "desc",
        "orderBy": "_count",
        "size": "20"
       },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Web - Source Countries",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 31 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "source.geo.country_name",
       "id": "2",
       "settings": {
        "min_doc_count": "1",
        "missing": "",
        "order": "desc",
        "orderBy": "_count",
        "size": "10"
       },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Web - Source IP",
   "type": "table",
   "gridPos": { "h": 18, "w": 5, "x": 6, "y": 31 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "source.ip",
       "id": "2",
       "settings": {
        "min_doc_count": "1",
        "missing": "",
        "order": "desc",
        "orderBy": "_count",
        "size": "20"
       },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Web - Source Countries(Geo)",
   "type": "geomap",
   "gridPos": { "h": 18, "w": 14, "x": 10, "y": 31 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "source.geo.country_iso_code",
       "id": "2",
       "settings": {
        "min_doc_count": "1",
        "missing": "",
        "order": "desc",
        "orderBy": "_count",
        "size": "100"
       },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Web - Source AS",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 40 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "source.as.organization.name",
       "id": "2",
       "settings": {
        "min_doc_count": "1",
        "missing": "",
        "order": "desc",
        "orderBy": "_count",
        "size": "10"
       },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Web - Request Method / Date Histogram",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 49 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "http.request.method",
       "id": "2",
       "settings": {
        "min_doc_count": "1",
        "missing": "",
        "order": "desc",
        "orderBy": "_count",
        "size": "10"
       },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "3", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Web - Status Code / Date Histogram",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 49 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" },
      {
       "field": "http.response.status_code",
       "id": "3",
       "settings": {
        "min_doc_count": "1",
        "missing": "",
        "order": "desc",
        "orderBy": "_count",
        "size": "8"
       },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Web - Heatmap (Request / Response)",
   "type": "heatmap",
   "gridPos": { "h": 15, "w": 20, "x": 0, "y": 59 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "http.request.method",
       "id": "2",
       "settings": {
        "min_doc_count": "1",
        "missing": "",
        "order": "desc",
        "orderBy": "_count",
        "size": "6"
       },
       "type": "terms"
      },
      {
       "field": "http.response.status_code",
       "id": "3",
       "settings": {
        "min_doc_count": "1",
        "missing": "",
        "order": "desc",
        "orderBy": "_count",
        "size": "8"
       },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Web - URL Extension",
   "type": "table",
   "gridPos": { "h": 15, "w": 4, "x": 20, "y": 59 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "url.extension",
       "id": "2",
       "settings": {
        "min_doc_count": "1",
        "missing": "",
        "order": "desc",
        "orderBy": "_count",
        "size": "20"
       },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Web - URL Domain",
   "type": "table",
   "gridPos": { "h": 18, "w": 6, "x": 0, "y": 74 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "url.domain",
       "id": "2",
       "settings": {
        "min_doc_count": "1",
        "missing": "",
        "order": "desc",
        "orderBy": "_count",
        "size": "100"
       },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Web - URL Path",
   "type": "table",
   "gridPos": { "h": 18, "w": 9, "x": 6, "y": 74 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "url.path",
       "id": "2",
       "settings": {
        "min_doc_count": "1",
        "missing": "",
        "order": "desc",
        "orderBy": "_count",
        "size": "200"
       },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Web - URL Query String",
   "type": "table",
   "gridPos": { "h": 18, "w": 10, "x": 14, "y": 74 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "url.query",
       "id": "2",
       "settings": {
        "min_doc_count": "1",
        "missing": "",
        "order": "desc",
        "orderBy": "_count",
        "size": "30"
       },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Web - User Agent Original",
   "type": "table",
   "gridPos": { "h": 18, "w": 9, "x": 0, "y": 92 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "user_agent.original",
       "id": "2",
       "settings": {
        "min_doc_count": "1",
        "missing": "",
        "order": "desc",
        "orderBy": "_count",
        "size": "20"
       },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Web - Referer",
   "type": "table",
   "gridPos": { "h": 18, "w": 10, "x": 9, "y": 92 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "http.request.referrer",
       "id": "2",
       "settings": {
        "min_doc_count": "1",
        "missing": "",
        "order": "desc",
        "orderBy": "_count",
        "size": "50"
       },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Web - EC2 Instance",
   "type": "table",
   "gridPos": { "h": 18, "w": 5, "x": 19, "y": 92 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "cloud.instance.id",
       "id": "2",
       "settings": {
        "min_doc_count": "1",
        "missing": "",
        "order": "desc",
        "orderBy": "_count",
        "size": "100"
       },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Web - User Agent OS Name",
   "type": "piechart",
   "gridPos": { "h": 14, "w": 8, "x": 0, "y": 110 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "user_agent.os.name",
       "id": "2",
       "settings": {
        "min_doc_count": "1",
        "missing": "",
        "order": "desc",
        "orderBy": "_count",
        "size": "10"
       },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Web - User Agent Device Name",
   "type": "piechart",
   "gridPos": { "h": 14, "w": 8, "x": 8, "y": 110 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "user_agent.device.name",
       "id": "2",
       "settings": {
        "min_doc_count": "1",
        "missing": "",
        "order": "desc",
        "orderBy": "_count",
        "size": "20"
       },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Web - User Agent Name",
   "type": "piechart",
   "gridPos": { "h": 14, "w": 8, "x": 16, "y": 110 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "user_agent.name",
       "id": "2",
       "settings": {
        "min_doc_count": "1",
        "missing": "",
        "order": "desc",
        "orderBy": "_count",
        "size": "20"
       },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Web - IoC matched Provider",
   "type": "table",
   "gridPos": { "h": 18, "w": 11, "x": 0, "y": 124 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "threat.matched.providers",
       "id": "2",
       "settings": {
        "min_doc_count": "1",
        "missing": "",
        "order": "desc",
        "orderBy": "_count",
        "size": "30"
       },
       "type": "terms"
      },
      {
       "field": "threat.matched.names",
       "id": "3",
       "settings": {
        "min_doc_count": "1",
        "missing": "",
        "order": "desc",
        "orderBy": "_count",
        "size": "30"
       },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "meta": { "customLabel": "Count" }, "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Web - IoC Matched IP Address",
   "type": "table",
   "gridPos": { "h": 18, "w": 6, "x": 11, "y": 124 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "threat.matched.indicators",
       "id": "2",
       "settings": {
        "min_doc_count": "1",
        "missing": "",
        "order": "desc",
        "orderBy": "_count",
        "size": "30"
       },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "meta": { "customLabel": "Count" }, "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Web - Response Size by Source IP",
   "type": "table",
   "gridPos": { "h": 18, "w": 7, "x": 17, "y": 124 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "source.ip",
       "id": "2",
       "settings": {
        "min_doc_count": "1",
        "missing": "",
        "order": "desc",
        "orderBy": "_count",
        "size": "30"
       },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "http.response.body.bytes", "id": "1", "meta": { "customLabel": "Bytes" }, "type": "sum" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "search - Web Access (service.name, @log_type, source.ip, source.geo.country_name, http.request.method, url.path, http.response.status_code, url.query, url.extension)",
   "type": "logs",
   "gridPos": { "h": 21, "w": 24, "x": 0, "y": 142 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "type": "logs" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "search - Web Error (service.name, @log_type, source.ip, log.level, error.code, error.message)",
   "type": "logs",
   "gridPos": { "h": 24, "w": 24, "x": 0, "y": 163 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "type": "logs" }
     ],
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}